sudo: required
services:
 - docker


before_install:
 - docker build -t azelante/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true azelante/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker"
 enviroment: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-2-099390798108"
 bucket_app: "docker"
 on:
  branch: master
 access_key_id: "$AWS_ACCESS_KEY"
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
 
 